"""remove customer id as foreign key

Revision ID: 630ad9c92f21
Revises: 81227084567e
Create Date: 2025-09-06 19:51:46.317167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630ad9c92f21'
down_revision = '81227084567e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
