"""remove customer id as foreign key

Revision ID: 81227084567e
Revises: 21cfb70a3edd
Create Date: 2025-09-06 19:44:42.537579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81227084567e'
down_revision = '21cfb70a3edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_signups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('newsletter_signups_customer_id_fkey'), type_='foreignkey')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('newsletter_signups_customer_id_fkey'), 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###
